enum custom_keycodes {
  SEL_WORD = SAFE_RANGE,
  COMBO_WH,
  COMBO_GH,
  COMBO_CH,
  COMBO_SH,
  COMBO_TH,
  COMBO_PH,

  // From Svalboard
  SV_LEFT_DPI_INC,
  SV_LEFT_DPI_DEC,
  SV_RIGHT_DPI_INC,
  SV_RIGHT_DPI_DEC,
  SV_LEFT_SCROLL_TOGGLE,
  SV_RIGHT_SCROLL_TOGGLE,
  SV_RECALIBRATE_POINTER,
  KC_NORMAL_HOLD,
  KC_FUNC_HOLD,
  SV_SET_DEADZONE,
 };
